frase = input('Digite algo: ')
print(f'O tipo primitivo desse valor é: {type(frase)}')
print(f'Só tem espaços? {frase.isspace()}')
print(f'É um numero? {frase.isnumeric()}')
print(f'É alfabético? {frase.isalpha()}')
print(f'É alfanumérico? {frase.isalnum()}')
print(f'Está em maiusculo? {frase.isupper()}')
print(f'Está em minusculo? {frase.islower()}')
print(f'Esta capitalizado? {frase.istitle()}')
